-- Migration number: 0001 	 2023-12-17T19:00:20.886Z
CREATE TABLE links (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
